### ISSUE TITLE
GCN Question: How is the whole graph information combined to make predictions?

### ISSUE THREAD

**Issue by jrhorne** [gitter-lab/nn4dms#2]
Hello! Awesome work!

I had a quick question from the manuscript where it states 

> "The final output of the network is computed at the graph-level with a single function score prediction for the entire graph."

— how exactly is the graph's node information combined into the final prediction? I tried looking in this repo, but I'm not familiar with TF v1 to know where to look. Is the node information all combined (added, averaged, concatenated, etc.) then connected to the final dense layer?

Sorry if I just missed this somewhere; thanks!

**Comment by samgelman** [comment]
Hi -- thanks for your interest in this work! 

The node information is concatenated / flattened before being fed into the final dense layer. The GCN architectures are defined in the [network_specs](https://github.com/gitter-lab/nn4dms/tree/master/network_specs/gcns) directory and the actual GCN layer is implemented in [my_pipgcn.py](https://github.com/gitter-lab/nn4dms/blob/master/code/my_pipgcn.py).
