### ISSUE TITLE
the CNN Model on protein bgl3 to reproduce the result

### ISSUE THREAD

**Issue by hurraygong** [gitter-lab/nn4dms#3]
Hi,

I am currently trying to run the CNN Model on protein bgl3 to reproduce the result. However, I got the following result.

====================
              mse  pearsonr          r2  spearmanr
set
train  349.179365 -0.002877 -176.620914  -0.000626
tune   376.436725  0.013659 -194.404795   0.000380
test   363.167681 -0.023509 -184.839247  -0.005544

the command to run is (Hyperparamters are in supplemental table):
python code/regression.py --dataset_name GBL3 --net_file network_specs/cnn-1xk17f32.yml --encoding one_hot,aa_index --batch_size 32 --learning_rate 0.0001 --log_dir_base output/training_logs --epochs 300 --early_stopping --train_size 0.6 --tune_size 0.2 --test_size 0.2 --split_rseed 9

I was wondering how to get the Pearson's r to 0.5? Is there error in the run command? Could help me check it?

**Comment by samgelman** [comment]
Hello! Can you please try the following command? 
`python code/regression.py @pub/regression_args/bgl3_main_cnn.txt`
It should train the Bgl3 CNN using the same train/val/test split and hyperparameters we used in the paper.

**Comment by agitter** [comment]
@hurraygong hopefully that gives you everything you need. Please feel free to reopen this if you have additional questions.

**Comment by AFVzhou** [comment]
@hurraygong Hello, I am currently trying to run the CNN Model on protein bg1 to reproduce the result. However, I got this error :
 FileNotFoundError:  No such file or directory: 'network_specs/cnn-1xk17f256. yml' 
the command to run is:
python code/regression.py --dataset_name gb1 --net_file network_specs/cnn-1xk17f256.yml --encoding one_h
ot,aa_index --batch_size 32 --learning_rate 0.0001 --log_dir_base output/training_logs --epochs 300 --early_stopping --train_size 0.6 --
tune_size 0.2 --test_size 0.2 --split_rseed 9
May I ask if you have encountered this mistake? Is it my improper operation?I am looking forward to your reply and wish you a pleasant life.
