### ISSUE TITLE
A custom network error

### ISSUE THREAD

**Issue by AFVzhou** [gitter-lab/nn4dms#9]
Hello, what should I do if I want to use my custom network structure to manipulate this data and train it? My custom network structure looks like this：
`network:
  - layer_func: ~tf.expand_dims
    arguments:
        input: ~layers[-1]
        axis: -1
  - layer_func: ~tf.layers.conv2d
    arguments:
      name: conv1
      inputs: ~layers[-1]
      filters: 64
      kernel_size: [5, '~layers[-1].shape[2]']
      strides: [1, 1]
      padding: valid
      activation: ~tf.nn.relu

  - layer_func: ~tf.layers.max_pooling1d
    arguments:
      name: pool1
      inputs: ~layers[-1]
      pool_size: 2
      strides: 2
      padding: valid

  - layer_func: ~tf.layers.conv2d
    arguments:
      name: conv2
      inputs: ~layers[-1]
      filters: 128
      kernel_size: [5, '~layers[-1].shape[2]']
      strides: [1, 1]
      padding: valid
      activation: ~tf.nn.relu

  - layer_func: ~tf.layers.max_pooling1d
    arguments:
      name: pool2
      inputs: ~layers[-1]
      pool_size: 2
      strides: 2
      padding: valid

  - layer_func: ~tf.layers.flatten
    arguments:
      inputs: ~layers[-1]

  - layer_func: ~tf.layers.dense
    arguments:
      name: dense1
      inputs: ~layers[-1]
      units: 256
      activation: ~tf.nn.relu

  - layer_func: ~tf.layers.dropout
    arguments:
      inputs: ~layers[-1]
      rate: 0.3
      training: ~ph_inputs_dict["training"]

  - layer_func: ~tf.layers.dense
    arguments:
      name: output
      inputs: ~layers[-1]
      units: 1
      activation: None`
Accordingly, I also created the document bgl3_main_cnn_network.txt. But when I run it, I get this error:
` Input 0 of layer pool1 is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [None, 497, 1, 64]`
Is there any operation I missed. Looking forward to your reply very much.

**Comment by agitter** [comment]
Thanks for reporting this @AFVzhou. We'll look into this and reply with more details when we have a suggestion for you to try.

**Comment by AFVzhou** [comment]
Thank you very much and look forward to your next reply

**Comment by AFVzhou** [comment]
Hi, I tried again and found that my custom network structure works successfully, My custom network structure looks like this：
network:
  - layer_func: ~tf.expand_dims
    arguments:
      input: ~layers[-1]
      axis: -1

  - layer_func: ~tf.layers.conv2d
    arguments:
      name: conv1
      inputs: ~layers[-1]
      filters: 256
      kernel_size: [ 17, '~layers[-1].shape[2]' ] 
      strides: [ 1, 1 ]
      padding: valid
      activation: ~tf.nn.leaky_relu

  - layer_func: ~tf.layers.flatten
    arguments:
      inputs: ~layers[-1]

  - layer_func: ~tf.layers.dense
    arguments:
      name: dense1
      inputs: ~layers[-1]
      units: 100
      activation: ~tf.nn.leaky_relu
      kernel_regularizer: ~tf.contrib.layers.l2_regularizer(scale=0.01)

  - layer_func: ~tf.layers.dropout
    arguments:
      inputs: ~layers[-1]
      rate: 0.2
And,I would like to know what format requirements are required for a custom network to work correctly.Looking forward to your reply.

**Comment by samgelman** [comment]
Hello!

The problem in the first example is a data shape mismatch between `conv2d` and `max_pooling1d`. Please try using `max_pooling2d` as follows:

```
- layer_func: ~tf.compat.v1.layers.max_pooling2d
  arguments:
    name: pool1
    inputs: ~layers[-1]
    pool_size: [2, 1]
    strides: [2, 1]
    padding: valid
```

Note that the `pool_size` and `strides` are defined as `[2, 1]`. Specifying the second dimension as `1` is necessary to match the output of `conv2d` and correctly process the 1D sequence. You can set the other dimension to your desired pool size and strides. 

In the second example, the dropout layer needs to have `training: ~ph_inputs_dict["training"]` as an argument to make sure dropout works as intended during training and inference. 

Please let me know if that works for you and if you have any more questions!

**Comment by samgelman** [comment]
One more note about the first example. There is no need to define a final output layer in the network architecture. The underlying code will automatically add a dense layer with 1 output node and no activation function to serve as the final output layer.

**Comment by AFVzhou** [comment]
Hello,after your answer I have retried example 1,structure looks like this:
`- network:
  - layer_func: ~tf.expand_dims
    arguments:
      input: ~layers[-1]
      axis: -1

  - layer_func: ~tf.layers.conv2d
    arguments:
      name: conv1
      inputs: ~layers[-1]
      filters: 128
      kernel_size: [17, '~layers[-1].shape[2]']
      strides: [1, 1]
      padding: valid
      activation: ~tf.nn.leaky_relu

  - layer_func: ~tf.layers.max_pooling2d
    arguments:
      name: pool1
      inputs: ~layers[-1]
      pool_size: [2,1]
      strides: [2,1]
      padding: valid

  - layer_func: ~tf.layers.conv2d
    arguments:
      name: conv2
      inputs: ~layers[-1]
      filters: 128
      kernel_size: [17, '~layers[-1].shape[2]']
      strides: [1, 1]
      padding: valid
      activation: ~tf.nn.leaky_relu

  - layer_func: ~tf.layers.max_pooling2d
    arguments:
      name: pool2
      inputs: ~layers[-1]
      pool_size: [2,1]
      strides: [2,1]
      padding: valid

  - layer_func: ~tf.layers.flatten
    arguments:
      inputs: ~layers[-1]

  - layer_func: ~tf.layers.dense
    arguments:
      name: dense1
      inputs: ~layers[-1]
      units: 100
      activation: ~tf.nn.leaky_relu

  - layer_func: ~tf.layers.dropout
    arguments:
      inputs: ~layers[-1]
      rate: 0.2
      training: ~ph_inputs_dict["training"]`
This error has occurred: UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 268: illegal multibyte sequence.
Please help me, how should I solve this problem, thank you very much

**Comment by samgelman** [comment]
This error suggests there is an encoding mismatch between the yaml file and the encoding Python is using to read the file. This could happen depending on your system/locale. Can you please attach the yaml file you are using?

In the meantime, you can try to explicitly specify utf-8 encoding. Change line 31 of `build_tf_model.py` to 
```python
with open(net_fn, "r", encoding="utf-8") as f:
````

**Comment by AFVzhou** [comment]
Hello, thank you again. If I want to add an attention mechanism module to the CNN network model, where should I write the module code and what changes should I make? Thank you very much.

**Comment by agitter** [comment]
The nn4dms code does not support attention mechanisms, and they may be hard to add in this version of TensorFlow. If you want to make that substantial of a modification you're welcome to try it, but it is outside the scope of what we can support.

If you want to use attention-based models, you may be interested in our recent model METL:
- repo: https://github.com/gitter-lab/metl
- preprint: [Biophysics-based protein language models for protein engineering](https://doi.org/10.1101/2024.03.15.585128)
